theme: minima

title: Tetsu Kayama  daily report
author: kayamatetsu
email: mail@kayamatetsu.com

gems:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  
# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Explicitly turn off the old code
paginate: 4
paginate_path: "page/page:num"

# Pagination Settings
pagination:
  enabled: true
  per_page: 4
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
